### ISSUE TITLE
"getCombatTrackerEntryContext" is not being called

### ISSUE THREAD

**Issue by manuelVo** [sfuqua/fvtt-hidden-initiative#8]
The hook "getCombatTrackerEntryContext" is called by foundries default combat tracker to allow modules to add entries to the context menu of combatants. When Hidden Initiative is enabled, this call is no longer made, which causes the context menu entries of modules like Drag Ruler to be missing from the combat tracker.

**Comment by sfuqua** [comment]
Good bug, thanks. I believe I have the root cause and it's... unfortunate. I'll see if I can work around this problem.

**Comment by sfuqua** [comment]
This should be fixed in 1.0.0 which I just released for 0.8.5 compatibility. I'm not super happy with the workaround but I think it's safe and will follow up with folks in Discord. I think there's an inconsistency with how Foundry is calling different types of hooks when CombatTracker is subclasses - `renderCombatTracker` behaves differently from `getCombatTrackerEntryContext`, for example.

**Comment by manuelVo** [comment]
Oh, that's quite the devious issue. Maybe it's worth opening an issue in the foundry bug tracker about this behavior. I guess other modules are likely affected by this as well and just haven't noticed yet...

For the time being I think your workaround is pretty good

**Comment by sfuqua** [comment]
Good idea! https://gitlab.com/foundrynet/foundryvtt/-/issues/5189

In filing the issue I actually found a bug in my fix - shouldn't impact Drag Ruler (`getCombatTrackerEntryContext` is working now) but I had the second hook wrong. Will get that patched shortly.
